title: Tab CI
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
header:
  title: Tab CI
  has_nav: true
  nav_links:
    - label: Features
      url: /features
      style: link
    - label: Contact Us
      url: /contact
      style: primary
footer:
  has_nav: true
  nav_links:
    - label: Contact Us
      url: /contact
      style: link
    - label: Privacy and Terms
      url: /terms
      style: link
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/byldworks'
      style: link
      new_window: true
  content: >-
    &copy; Byldworks Limited. All rights reserved.
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://tab-ci-web-5d49e.netlify.app'
